---
date: 2025-07-02 10:15
modified: 2025-07-03 11:15
---

# 函数运行的三种状态

![[函数运行的三种状态.excalidraw]]

# Generator 特性

## 可交出执行权，可暂停可恢复

Generator 函数是协程在 ES6 的实现，最大特点就是可以交出函数的执行权（即暂停执行）

```js
function* test() {
    console.log('1111');
    yield;
    console.log('3333');
}

const g = test();
g.next();           // 1111
console.log('2222') // 2222

g.next()            // 3333
```

Generator 函数不同于普通函数，是可以暂停执行的，所以函数名之前要加星号，以示区别

整个 Generator 函数就是一个封装的异步任务，或者说是异步任务的容器。异步操作需要暂停的地方，都用 `yield` 语句注明

调用 Generator 函数，会返回一个内部指针（即[遍历器]( https://link.juejin.cn/?target=https%3A%2F%2Fes6.ruanyifeng.com%2F%23docs%2Fiterator " https://es6.ruanyifeng.com/#docs/iterator" ) ）`g`

调用指针 `g` 的 `next` 方法，会移动内部指针（即执行异步任务的第一段），指向第一个遇到的 `yield` 语句为止

换言之，`next` 方法的作用是分阶段执行 `Generator` 函数。每次调用 `next` 方法，会返回一个对象，表示当前阶段的信息：

```js
{
    done: true/false,
    value: xxx,
}
```

- `done`：一个布尔值，表示 Generator 函数是否执行完毕，即是否还有下一个阶段
- `value`：`yield` 语句后面表达式的值，表示当前阶段的返回值

## 函数体内外的数据交换

- `next` 方法返回值的 `value` 属性，是 Generator 函数向外输出数据
- `next` 方法还可以接受参数，这是向 Generator 函数体内输入数据

```js
function* gen(x) {
  var y = yield x + 2;
  return y;
}

var g = gen(1);
g.next()  // { value: 3, done: false }
g.next(2) // { value: 2, done: true }
```

上面代码中，第一个 `next` 方法的 `value` 属性，返回表达式 `x + 2` 的值。第二个 `next` 方法带有参数 `2`，这个参数可以传入 Generator 函数，作为上个阶段异步任务的返回结果，被函数体内的变量 `y` 接收。因此，这一步的 `value` 属性，返回的就是 `2`（变量 `y` 的值）

## 错误处理

Generator 函数内部还可以部署错误处理代码，捕获函数体外抛出的错误

```js
function* gen(x) {
  let y;
  try {
    y = yield x + 2;
  } catch (e) { 
    console.log(e); // 此处打印出错了
  }
  return y;
}

var g = gen(1);
console.log(g.next()); 
console.log(g.throw('出错了'));  // 被 catch 捕获

// 打印结果：
//     { value: 3, done: false }
//     出错了
//     { value: undefined, done: true }
```

上面代码的最后一行，Generator 函数体外，使用指针对象的 `throw` 方法抛出的错误，可以被函数体内的 `try...catch` 代码块捕获。这意味着，出错的代码与处理错误的代码，实现了时间和空间上的分离，这对于异步编程无疑是很重要的
